call plug#begin('~/.vim/plugged')

Plug 'junegunn/seoul256.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'tpope/vim-surround'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'easymotion/vim-easymotion'
Plug 'jiangmiao/auto-pairs'
Plug 'itchyny/lightline.vim'

call plug#end()


filetype plugin on
syntax on
set backspace=indent,eol,start
"colo molokai
"colo solarized
colo seoul256
"set cursorline
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
set ignorecase
set smartcase
" set foldmethod=indent
au FileType *.groovy | Goyo

" seoul256 (dark):
"   Range:   233 (darkest) ~ 239 (lightest)
"   Default: 237
let g:seoul256_background = 235
"colo seoul256

autocmd VimEnter * Goyo 100


function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
  "Limelight 0.6
endfunction

function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
  "Limelight!
endfunction

autocmd! User GoyoEnter call <SID>goyo_enter()
autocmd! User GoyoLeave call <SID>goyo_leave()

map + :Limelight 0.6 <CR>
map _ :Limelight! <CR>
map  / <Plug>(easymotion-sn)
nmap n <Plug>(easymotion-next)

set background=dark
set laststatus=2
let g:lightline = { 'colorscheme': 'seoul256' }
set noshowmode
